services:
  db:
    image: postgres:16-alpine
    container_name: axiom_quant_db
    env_file:
      - ./.env
    volumes:
      - axiom_quant_db_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    container_name: axiom_quant_app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "axiomquant.api.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  axiom_quant_db_data: