name: AxiomQuant CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: axiom_quant_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Check formatting and linting
        run: |
          black --check .
          ruff check .

      - name: Run API Server in Background
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: axiom_quant_dev
        run: uvicorn axiomquant.api.main:app --host 0.0.0.0 --port 8000 &

      - name: Wait for API server to be ready
        run: |
          echo "Waiting for API..."
          timeout=30
          while ! curl -s --fail "http://localhost:8000/health"; do
            sleep 1
            timeout=$((timeout-1))
            if [ $timeout -le 0 ]; then
              echo "Error: API server did not start in time."
              exit 1
            fi
          done
          echo "API server is ready."

      - name: Run tests with pytest
        run: pytest